# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, workflows ]
  pull_request:
    branches: [ master, workflows ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build JARs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "<settings><servers><server><id>github</id><username>ovh</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        make test
        make deploy
    - name: Build Docker images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u ovh --password-stdin
        docker build --build-arg MAVEN_PROFILE=tensorflow -t docker.pkg.github.com/ovh/serving-runtime/api-tf:latest -f dockerfiles/tensorflow.Dockerfile .
        docker push docker.pkg.github.com/ovh/serving-runtime/api-tf:latest
